# Numpy
- it gives efficient storage
- it also provides better ways of handling data for processing
- it is fast
- it is easy to learn
- numpy uses relatively less memory to store data






In [157]:
import numpy as np


In [158]:
myarr = np.array([3,64,32,7], np.int64)

In [159]:
myarr[0]

np.int64(3)

In [160]:
myarr.shape

(4,)

In [161]:
myarr.dtype

dtype('int64')

In [162]:
myarr[0] = 67

In [163]:
myarr[0]

np.int64(67)

# Array Creation Methods

### there are 5 general mechanisms for creating arrays

1. Conversion from other python structures(lists, tuples)

In [164]:
arr = np.array([[2,3,4,5]])
arr.shape
arr.sum()
arr.shape
arr.sort()
arr
arr.dtype

dtype('int64')

In [165]:

arr = np.array({12, 45, 45})

arr

array({12, 45}, dtype=object)

2. Intrinsic numpy array creation(arrange, ones, zeroes)

In [166]:
zeros = np.zeros([2,5])
zeros # will give 2d array of 2 rows, 5 columns with zeros
zeros.dtype
zeros.shape


(2, 5)

In [167]:
rng = np.arange(15)
rng # will give 0 to 14 numpy array


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [168]:
lspace = np.linspace(1,5,7)
# to get equally linearly spaced elements
lspace # it will start from 1 and to 5
#  will give 7 equal parts of values
# which means lspace will divide the values such that every value to value difference is same, along side the range is in between 1,5 adn staring from 1

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        ])

In [169]:
emp = np.empty([2,3])
# will give an array filled with random elements
emp
emp.dtype

dtype('float64')

In [170]:
emp_like = np.empty_like(lspace)
emp_like

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        ])

In [171]:
ide = np.identity(7)
# will give the 7*7 identity matrix
ide.shape
ide

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [172]:
a = np.arange(77)
a = a.reshape(7,11)

In [173]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76]])

In [174]:
a. shape
a= a.ravel() # will change to 1D array again
a.shape
for i in a.flat: # it will give an iterable
    print(i)
a.ndim # no. of dimensions
a.size # no.of elements
a.nbytes # no. of bytes required to store the data in that array
a

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76])

In [175]:
one = np.array([1,2,5,4,3,3])
one.argmax() # it gives the index at which the maximum value is present
one.argmin()
one.argsort() # it will give the indexes in increasing order of elements


array([0, 1, 5, 4, 3, 2])

In [176]:
ar = np.array([[1,2,3],[4,5,6],[7,1,0]])
ar.argmin() # 8
ar.argmax() # 6
ar.argmax(axis=0) # [2,1,1] -> indexes
ar.argmax(axis=1) #  [2,2,0] -> indexes

ar.argsort(axis=0) # observe here something is different...


array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [177]:

ar.ravel()
ar.reshape(9,)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [183]:
ar2 = np.array([[1,2,1],
                [4,0,6],
                [8,1,0]])
ar2 + ar
[32,43] + [98,90] # we cannon add two lists in python
# but using numpy we can be able to perform such operations



[32, 43, 98, 90]

In [195]:
np.sqrt(ar2)
np.sum(ar2)
ar2.sum()
ar2.min()
np.where(ar2>3)
np.count_nonzero(ar2)

7

### How is Numpy taking less space

In [196]:
import sys

In [198]:
py_ar = [0,4,55,2]
np_arr = np.array(py_ar)

In [199]:
sys.getsizeof(1)*len(py_ar)

112

In [200]:
np_arr.itemsize * np_arr.size

32

search for numpy array methods and attributes


##### Numpy Axis
1D -> [1,2,3,4,5]  -> only 1 axis(axis = 0) <br>
2D -> [[1,2] , [3,4]] -> only 2 axises(axis=0, axis=1)

axis = 0, means columns<br>
axis = 1, means rows





3. Reading arrays from disk, either from standard or custom formats

4.  Creating arrays from disk, eithere from standard or custom formats

5. Use of special library functions